version: '3.8'
services:
  python-gui:
    build: .
    container_name: python_gui_app
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./src:/app
    command: tail -f /dev/null
    # Uncomment the following lines if running on Linux with X11
    # devices:
    #   - "/dev/dri:/dev/dri"
    # network_mode: host
    # privileged: true
    # For Windows/Mac, you may need to use X11 forwarding or VcXsrv/XQuartz
    # and set DISPLAY accordingly
    # Example for Windows:
    # environment:
    #   - DISPLAY=host.docker.internal:0.0
    ports:
       - "8000:8000"
    # depends_on:
    #   - esp32-backend